blank_issues_enabled: false
contact_links:
  - about: Discuss the future of LIT community in the discussions and proposals repository.
    name: 🚀 Discussions and Proposals
    url: 'https://github.com/latina-in-tech/latina-in-tech.github.io/discussions/new/choose'