import Thumbnail from '@/components/Thumbnail';
import { IPost } from '@/model/post';
import { getAllPosts } from '@/utils/mdxUtils';
import { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

// props type
type Props = {
  posts: [IPost];
};

const Home: NextPage<Props> = ({ posts }: Props) => {
  return (
    <>
      <Head>
        <title>LiT - Latina In Tech</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <meta
          name='description'
          content='Community che raccoglie gli sviluppatori della provincia di Latina'
        />
        <meta
          name='keywords'
          content='Latina, User Group, Lazio, Roma, Sviluppatori Latina, Latina In Tech, LiT'
        ></meta>
        <link rel='icon' href='/favicon.ico' />
        <link rel='manifest' href='/manifest.json' />
      </Head>
      <main>
        <div>
          <h1 className='text-4xl font-bold mb-4'>Technical articles</h1>

          <div className='space-y-12'>
            {posts.map((post) => (
              <div key={post.slug}>
                <div className='mb-4'>
                  <Thumbnail
                    slug={post.slug}
                    title={post.title}
                    src={post.thumbnail}
                  />
                </div>

                <h2 className='text-2xl font-bold mb-4'>
                  <Link href={`/posts/${post.slug}`}>{post.title}</Link>
                </h2>

                <p>{post.description}</p>
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

// get posts from serverside at build time
export const getStaticProps: GetStaticProps = async () => {
  const posts = getAllPosts([
    'title',
    'slug',
    'date',
    'description',
    'thumbnail',
  ]);

  // retunr the posts props
  return { props: { posts } };
};
